services:
  postgres:
    image: postgres:17
    container_name: egov_postgres
    restart: always
    environment:
      POSTGRES_DB: egovdb
      POSTGRES_USER: egov
      POSTGRES_PASSWORD: egov
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
